/*
 * ForgeCoach — scripts/j111-blue/gen.ts
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Writes src/draft/blueJ111.ts from mtg-table's lab result J111
 * (`results/J111/blue.json` on its `pc-results` branch): per cube, how much
 * blue the lab's AI drafter takes against what the cube's colour balance
 * predicts, and how blue decks played by Forge win at equal deck quality.
 * Numbers only; nothing here changes a score, a rating or the drafter.
 *
 *   node --experimental-transform-types scripts/j111-blue/gen.ts <blue.json> [out.ts]
 *
 * `blueRowsFrom` and `renderModule` are pure (tested in gen.test.ts).
 */

export interface BlueRow {
  /** ForgeCoach's cube id (cubes.ts), J111's `key`. */
  cube: string;
  /** Drafts kept for the rates. */
  drafts: number;
  /** Share of the AI drafter's decks that play blue. */
  deckShare: number;
  /** The blue deck share the cube's colour balance predicts. */
  expectedShare: number;
  /** deckShare / expectedShare, as J111 writes it. */
  overFactor: number;
  /** Blue decks' win rate at equal deck quality (uncontested, card-score quality), with its 95% interval. */
  equalQualityWin: number;
  equalQualityLo: number;
  equalQualityHi: number;
}

type Obj = Record<string, unknown>;
const obj = (x: unknown, what: string): Obj => {
  if (!x || typeof x !== 'object' || Array.isArray(x)) throw new Error(`blue.json: ${what} is not an object`);
  return x as Obj;
};
const num = (x: unknown, what: string, lo: number, hi: number): number => {
  if (typeof x !== 'number' || !Number.isFinite(x) || x < lo || x > hi) throw new Error(`blue.json: ${what} is not a number in [${lo}, ${hi}]`);
  return x;
};

/** J111's per-cube rows, sorted by cube id. Throws on anything unexpected. */
export function blueRowsFrom(json: unknown): BlueRow[] {
  const root = obj(json, 'the file');
  const per = obj(root.per_cube, 'per_cube');
  const rows: BlueRow[] = [];
  for (const [k, v] of Object.entries(per)) {
    const c = obj(v, k);
    const key = c.key;
    if (typeof key !== 'string' || !/^[a-z][a-z0-9-]*$/.test(key)) throw new Error(`blue.json: ${k}.key is not a cube id`);
    const rates = obj(c.rates, `${k}.rates`);
    const balance = obj(c.balance, `${k}.balance`);
    const m = obj(obj(c.score, `${k}.score`).uncontested_model, `${k}.score.uncontested_model`);
    if (m.ok !== 1) throw new Error(`blue.json: ${k}'s equal-quality model did not fit`);
    const ci = m.b0_rate_ci;
    if (!Array.isArray(ci) || ci.length !== 2) throw new Error(`blue.json: ${k}.score.uncontested_model.b0_rate_ci`);
    const row: BlueRow = {
      cube: key,
      drafts: num(rates.drafts, `${k}.rates.drafts`, 1, 1e9),
      deckShare: num(rates.blue_deck_share, `${k}.rates.blue_deck_share`, 0, 1),
      expectedShare: num(balance.expected_blue_deck_share, `${k}.balance.expected_blue_deck_share`, 0.01, 1),
      overFactor: num(c.blue_share_over_expected, `${k}.blue_share_over_expected`, 0, 100),
      equalQualityWin: num(m.b0_rate, `${k} b0_rate`, 0, 1),
      equalQualityLo: num(ci[0], `${k} b0_rate_ci[0]`, 0, 1),
      equalQualityHi: num(ci[1], `${k} b0_rate_ci[1]`, 0, 1),
    };
    if (!(row.equalQualityLo <= row.equalQualityWin && row.equalQualityWin <= row.equalQualityHi)) throw new Error(`blue.json: ${k}'s interval does not hold its rate`);
    rows.push(row);
  }
  if (!rows.length) throw new Error('blue.json: no cubes');
  return rows.sort((a, b) => (a.cube < b.cube ? -1 : 1));
}

/** The data module's source text. */
export function renderModule(rows: readonly BlueRow[]): string {
  const body = rows
    .map(
      (r) =>
        `  '${r.cube}': { drafts: ${r.drafts}, deckShare: ${r.deckShare}, expectedShare: ${r.expectedShare}, overFactor: ${r.overFactor}, equalQualityWin: ${r.equalQualityWin}, equalQualityLo: ${r.equalQualityLo}, equalQualityHi: ${r.equalQualityHi} },`,
    )
    .join('\n');
  return `/*
 * ForgeCoach — draft/blueJ111.ts
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by scripts/j111-blue/gen.ts from mtg-table's lab result J111
 * (results/J111/blue.json, pc-results branch). Do not edit by hand.
 *
 * Per cube: the share of the cube lab's AI-drafter decks that play blue, the
 * share the cube's colour balance predicts, their ratio, and blue decks' win
 * rate in Forge's hands at equal deck quality (uncontested, 95% interval).
 * Words only (draft/blueNote.ts): no score, rating or drafter reads this.
 */
export interface BlueStats {
  /** Drafts kept for the rates. */
  drafts: number;
  /** Share of the AI drafter's decks that play blue. */
  deckShare: number;
  /** The blue deck share the cube's colour balance predicts. */
  expectedShare: number;
  /** deckShare / expectedShare. */
  overFactor: number;
  /** Blue decks' win rate at equal deck quality, with its 95% interval. */
  equalQualityWin: number;
  equalQualityLo: number;
  equalQualityHi: number;
}

export const BLUE_J111: Readonly<Record<string, BlueStats>> = {
${body}
};
`;
}

async function main(args: string[]): Promise<number> {
  const [src, out = 'src/draft/blueJ111.ts'] = args;
  if (!src) {
    console.error('usage: gen.ts <blue.json> [out.ts]');
    return 2;
  }
  const { readFileSync, writeFileSync } = await import('node:fs');
  const rows = blueRowsFrom(JSON.parse(readFileSync(src, 'utf8')));
  writeFileSync(out, renderModule(rows));
  console.log(`${out}: ${rows.length} cubes (${rows.map((r) => r.cube).join(', ')})`);
  return 0;
}

if (typeof process !== 'undefined' && process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  process.exitCode = await main(process.argv.slice(2));
}
