/*
 * ForgeCoach — draft/blueJ111.ts
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * GENERATED by scripts/j111-blue/gen.ts from mtg-table's lab result J111
 * (results/J111/blue.json, pc-results branch). Do not edit by hand.
 *
 * Per cube: the share of the cube lab's AI-drafter decks that play blue, the
 * share the cube's colour balance predicts, their ratio, and blue decks' win
 * rate in Forge's hands at equal deck quality (uncontested, 95% interval).
 * Words only (draft/blueNote.ts): no score, rating or drafter reads this.
 */
export interface BlueStats {
  /** Drafts kept for the rates. */
  drafts: number;
  /** Share of the AI drafter's decks that play blue. */
  deckShare: number;
  /** The blue deck share the cube's colour balance predicts. */
  expectedShare: number;
  /** deckShare / expectedShare. */
  overFactor: number;
  /** Blue decks' win rate at equal deck quality, with its 95% interval. */
  equalQualityWin: number;
  equalQualityLo: number;
  equalQualityHi: number;
}

export const BLUE_J111: Readonly<Record<string, BlueStats>> = {
  'fair-fight': { drafts: 7434, deckShare: 0.7215, expectedShare: 0.3963, overFactor: 1.821, equalQualityWin: 0.3629, equalQualityLo: 0.3225, equalQualityHi: 0.4052 },
  'modern-era': { drafts: 7507, deckShare: 0.6172, expectedShare: 0.4018, overFactor: 1.536, equalQualityWin: 0.426, equalQualityLo: 0.3997, equalQualityHi: 0.4527 },
  'omega': { drafts: 6682, deckShare: 0.5919, expectedShare: 0.4019, overFactor: 1.473, equalQualityWin: 0.4621, equalQualityLo: 0.4305, equalQualityHi: 0.494 },
  'pauper': { drafts: 10370, deckShare: 0.8228, expectedShare: 0.3945, overFactor: 2.086, equalQualityWin: 0.3718, equalQualityLo: 0.3216, equalQualityHi: 0.425 },
  'peasant': { drafts: 10950, deckShare: 0.5575, expectedShare: 0.4037, overFactor: 1.381, equalQualityWin: 0.3995, equalQualityLo: 0.3803, equalQualityHi: 0.419 },
  'synergy': { drafts: 8758, deckShare: 0.6625, expectedShare: 0.4019, overFactor: 1.648, equalQualityWin: 0.3249, equalQualityLo: 0.2972, equalQualityHi: 0.3539 },
  'vintage': { drafts: 6560, deckShare: 0.6133, expectedShare: 0.4019, overFactor: 1.526, equalQualityWin: 0.4512, equalQualityLo: 0.4232, equalQualityHi: 0.4794 },
};
